import { test, expect } from '@playwright/test'
import { login } from './review-session.mjs'

// Reader view settings: the sidebar and the outline collapse on their own, and the view menu
// switches small text and full width. Everything is kept in one localStorage entry for every document.
const heading = '더 명확하게, 더 편안하게'
const openDocument = async (page, path = '/p/moa-design/overview') => {
  await page.goto(path)
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
}
const mockTools = page => page.route('**/api/claude', route => route.fulfill({ json: { 'moa-design': { skills: [], agents: [] } } }))
const sidebar = page => page.locator('aside').filter({ has: page.getByRole('combobox', { name: 'Switch project', exact: true }) })
const outline = page => page.getByRole('complementary', { name: 'Document outline', exact: true })
const article = page => page.locator('article.moa-prose')
const reading = page => page.locator('main#document-content')
const width = locator => locator.evaluate(element => element.getBoundingClientRect().width)
const storedView = page => page.evaluate(() => JSON.parse(localStorage.getItem('hub.reader.view')))
const noOverflow = async page => expect(await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)).toBeLessThanOrEqual(1)

test('the sidebar and the outline collapse separately, hand focus to the control that restores them, and stay collapsed after a reload', async ({ page }) => {
  await login(page)
  await mockTools(page)
  await openDocument(page)
  await expect(sidebar(page)).toBeVisible()
  await expect(outline(page)).toBeVisible()
  const initial = await width(reading(page))

  await sidebar(page).getByRole('button', { name: 'Hide sidebar', exact: true }).click()
  await expect(sidebar(page)).toHaveCount(0)
  const showSidebar = page.getByRole('button', { name: 'Show sidebar', exact: true })
  await expect(showSidebar).toBeFocused()
  await expect(outline(page)).toBeVisible()
  await expect.poll(() => width(reading(page))).toBeGreaterThan(initial)
  expect(await storedView(page)).toMatchObject({ sidebar: false, outline: true })
  const withoutSidebar = await width(reading(page))

  await outline(page).getByRole('button', { name: 'Hide outline', exact: true }).click()
  await expect(outline(page)).toBeHidden()
  const showOutline = page.getByRole('button', { name: 'Show outline', exact: true })
  await expect(showOutline).toBeFocused()
  await expect.poll(() => width(reading(page))).toBeGreaterThan(withoutSidebar)
  expect(await storedView(page)).toMatchObject({ sidebar: false, outline: false })
  await noOverflow(page)

  await page.reload()
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  await expect(sidebar(page)).toHaveCount(0)
  await expect(outline(page)).toBeHidden()
  await expect(showSidebar).toBeVisible()
  await expect(showOutline).toBeVisible()

  await showOutline.click()
  await expect(outline(page)).toBeVisible()
  await expect(outline(page).getByRole('button', { name: 'Hide outline', exact: true })).toBeFocused()
  await expect(showOutline).toHaveCount(0)
  await showSidebar.click()
  await expect(sidebar(page)).toBeVisible()
  await expect(sidebar(page).getByRole('button', { name: 'Hide sidebar', exact: true })).toBeFocused()
  await expect(showSidebar).toHaveCount(0)
  expect(await storedView(page)).toMatchObject({ sidebar: true, outline: true })
  expect(await width(reading(page))).toBe(initial)
})

test('small text and full width are switches in the view menu, change the document column, and apply to every document', async ({ page }) => {
  await login(page)
  await mockTools(page)
  await openDocument(page)
  await expect(article(page)).toHaveCSS('font-size', '17px')
  await expect(article(page)).toHaveCSS('max-width', '704px')
  const menu = page.getByRole('button', { name: 'View options', exact: true })
  await menu.click()
  await expect(menu).toHaveAttribute('aria-expanded', 'true')
  const smallText = page.getByRole('switch', { name: 'Small text', exact: true })
  const fullWidth = page.getByRole('switch', { name: 'Full width', exact: true })
  await expect(smallText).toBeFocused()
  await expect(smallText).toHaveAttribute('aria-checked', 'false')
  await expect(fullWidth).toHaveAttribute('aria-checked', 'false')

  await smallText.click()
  await expect(smallText).toHaveAttribute('aria-checked', 'true')
  await expect(article(page)).toHaveCSS('font-size', '15px')
  await fullWidth.click()
  await expect(fullWidth).toHaveAttribute('aria-checked', 'true')
  await expect(article(page)).toHaveCSS('max-width', 'none')
  expect(await width(article(page))).toBeGreaterThan(704)
  await noOverflow(page)
  expect(await storedView(page)).toMatchObject({ smallText: true, fullWidth: true })

  await page.keyboard.press('Escape')
  await expect(page.getByRole('switch')).toHaveCount(0)
  await expect(menu).toBeFocused()
  await expect(menu).toHaveAttribute('aria-expanded', 'false')

  // Another project's document reads the same way.
  await openDocument(page, '/p/brand-notes/overview')
  await expect(article(page)).toHaveCSS('font-size', '15px')
  await expect(article(page)).toHaveCSS('max-width', 'none')
  await menu.click()
  await page.getByRole('switch', { name: 'Small text', exact: true }).click()
  await page.getByRole('switch', { name: 'Full width', exact: true }).click()
  await expect(article(page)).toHaveCSS('font-size', '17px')
  await expect(article(page)).toHaveCSS('max-width', '704px')
  expect(await storedView(page)).toMatchObject({ smallText: false, fullWidth: false })
  await page.locator('article h1').click()
  await expect(page.getByRole('switch')).toHaveCount(0)
})

test('390px keeps the navigation drawer whatever the sidebar setting, and the view menu still applies', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await login(page)
  await mockTools(page)
  await page.addInitScript(() => localStorage.setItem('hub.reader.view', JSON.stringify({ sidebar: false, outline: false, smallText: false, fullWidth: false })))
  await openDocument(page)
  await expect(page.getByRole('button', { name: 'Show sidebar', exact: true })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Show outline', exact: true })).toBeHidden()
  const menu = page.getByRole('button', { name: 'Open document navigation', exact: true })
  await menu.click()
  const drawer = page.getByRole('dialog', { name: 'Document navigation', exact: true })
  await expect(drawer).toBeVisible()
  await expect(drawer.getByRole('navigation', { name: 'Project documents', exact: true })).toBeVisible()
  await expect(drawer.getByRole('button', { name: 'Hide sidebar', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(menu).toBeFocused()

  await expect(article(page)).toHaveCSS('font-size', '16px')
  await page.getByRole('button', { name: 'View options', exact: true }).click()
  await page.getByRole('switch', { name: 'Small text', exact: true }).click()
  await expect(article(page)).toHaveCSS('font-size', '15px')
  await noOverflow(page)
})

test('a shared document offers the view menu but no sidebar or outline controls it cannot use', async ({ page }) => {
  await page.goto('/s/review-document-link-only')
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /sidebar/ })).toHaveCount(0)
  await outline(page).getByRole('button', { name: 'Hide outline', exact: true }).click()
  await expect(outline(page)).toBeHidden()
  await page.getByRole('button', { name: 'View options', exact: true }).click()
  await page.getByRole('switch', { name: 'Full width', exact: true }).click()
  await expect(article(page)).toHaveCSS('max-width', 'none')
  await page.reload()
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  await expect(outline(page)).toBeHidden()
  await expect(article(page)).toHaveCSS('max-width', 'none')
  await page.getByRole('button', { name: 'Show outline', exact: true }).click()
  await expect(outline(page)).toBeVisible()
})
