import { test, expect } from '@playwright/test'
import { login } from './review-session.mjs'

// Reader view settings: the sidebar collapses from its own button, and the view menu switches small
// text, full width and the table of contents. Everything is kept in one localStorage entry for every document.
const heading = '더 명확하게, 더 편안하게'
const openDocument = async (page, path = '/p/moa-design/overview') => {
  await page.goto(path)
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
}
const mockTools = page => page.route('**/api/claude', route => route.fulfill({ json: { 'moa-design': { skills: [], agents: [] } } }))
const sidebar = page => page.locator('aside').filter({ has: page.getByRole('combobox', { name: 'Switch project', exact: true }) })
const outline = page => page.getByRole('complementary', { name: 'Document outline', exact: true })
const article = page => page.locator('article.moa-prose')
const reading = page => page.locator('main#document-content')
const width = locator => locator.evaluate(element => element.getBoundingClientRect().width)
const storedView = page => page.evaluate(() => JSON.parse(localStorage.getItem('hub.reader.view')))
const noOverflow = async page => expect(await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)).toBeLessThanOrEqual(1)
const openMenu = async page => {
  const menu = page.getByRole('button', { name: 'View options', exact: true })
  await menu.click()
  await expect(menu).toHaveAttribute('aria-expanded', 'true')
  return menu
}
const option = (page, name) => page.getByRole('switch', { name, exact: true })

test('the sidebar collapses from its own button, hands focus to the control that restores it, and stays collapsed after a reload', async ({ page }) => {
  await login(page)
  await mockTools(page)
  await openDocument(page)
  await expect(sidebar(page)).toBeVisible()
  await expect(outline(page)).toBeVisible()
  const initial = await width(reading(page))

  await sidebar(page).getByRole('button', { name: 'Hide sidebar', exact: true }).click()
  await expect(sidebar(page)).toHaveCount(0)
  const showSidebar = page.getByRole('button', { name: 'Show sidebar', exact: true })
  await expect(showSidebar).toBeFocused()
  await expect(outline(page)).toBeVisible()
  await expect.poll(() => width(reading(page))).toBeGreaterThan(initial)
  expect(await storedView(page)).toMatchObject({ sidebar: false, outline: true })
  await noOverflow(page)

  await page.reload()
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  await expect(sidebar(page)).toHaveCount(0)
  await expect(showSidebar).toBeVisible()

  await showSidebar.click()
  await expect(sidebar(page)).toBeVisible()
  await expect(sidebar(page).getByRole('button', { name: 'Hide sidebar', exact: true })).toBeFocused()
  await expect(showSidebar).toHaveCount(0)
  expect(await storedView(page)).toMatchObject({ sidebar: true })
  expect(await width(reading(page))).toBe(initial)
})

test('the table of contents is a switch in the view menu, widens the document when off, and steps aside with the AI assistant', async ({ page }) => {
  await login(page)
  await mockTools(page)
  await openDocument(page)
  await expect(outline(page)).toBeVisible()
  const initial = await width(reading(page))
  const menu = await openMenu(page)
  const contents = option(page, 'Table of contents')
  await expect(contents).toHaveAttribute('aria-checked', 'true')
  await contents.click()
  await expect(contents).toHaveAttribute('aria-checked', 'false')
  await expect(outline(page)).toBeHidden()
  await expect.poll(() => width(reading(page))).toBeGreaterThan(initial)
  expect(await storedView(page)).toMatchObject({ outline: false })
  await noOverflow(page)
  await page.keyboard.press('Escape')
  await expect(menu).toBeFocused()

  await page.reload()
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  await expect(outline(page)).toBeHidden()
  await openMenu(page)
  await option(page, 'Table of contents').click()
  await expect(outline(page)).toBeVisible()
  expect(await width(reading(page))).toBe(initial)
  await page.keyboard.press('Escape')

  // The assistant's column takes the outline's room, so the switch leaves the menu with it.
  await page.getByRole('button', { name: 'Open AI assistant', exact: true }).click()
  await expect(outline(page)).toBeHidden()
  await openMenu(page)
  await expect(option(page, 'Table of contents')).toBeHidden()
  await expect(option(page, 'Small text')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('banner').getByRole('button', { name: 'Close AI assistant', exact: true }).click()
  await expect(outline(page)).toBeVisible()
  await openMenu(page)
  await expect(option(page, 'Table of contents')).toBeVisible()
})

test('small text and full width are switches in the view menu, change the document column, and apply to every document', async ({ page }) => {
  await login(page)
  await mockTools(page)
  await openDocument(page)
  await expect(article(page)).toHaveCSS('font-size', '17px')
  await expect(article(page)).toHaveCSS('max-width', '704px')
  const menu = await openMenu(page)
  const smallText = option(page, 'Small text')
  const fullWidth = option(page, 'Full width')
  await expect(smallText).toBeFocused()
  await expect(smallText).toHaveAttribute('aria-checked', 'false')
  await expect(fullWidth).toHaveAttribute('aria-checked', 'false')

  await smallText.click()
  await expect(smallText).toHaveAttribute('aria-checked', 'true')
  await expect(article(page)).toHaveCSS('font-size', '15px')
  await fullWidth.click()
  await expect(fullWidth).toHaveAttribute('aria-checked', 'true')
  await expect(article(page)).toHaveCSS('max-width', 'none')
  expect(await width(article(page))).toBeGreaterThan(704)
  await noOverflow(page)
  expect(await storedView(page)).toMatchObject({ smallText: true, fullWidth: true })

  await page.keyboard.press('Escape')
  await expect(page.getByRole('switch')).toHaveCount(0)
  await expect(menu).toBeFocused()
  await expect(menu).toHaveAttribute('aria-expanded', 'false')

  // Another project's document reads the same way.
  await openDocument(page, '/p/brand-notes/overview')
  await expect(article(page)).toHaveCSS('font-size', '15px')
  await expect(article(page)).toHaveCSS('max-width', 'none')
  await openMenu(page)
  await option(page, 'Small text').click()
  await option(page, 'Full width').click()
  await expect(article(page)).toHaveCSS('font-size', '17px')
  await expect(article(page)).toHaveCSS('max-width', '704px')
  expect(await storedView(page)).toMatchObject({ smallText: false, fullWidth: false })
  await page.locator('article h1').click()
  await expect(page.getByRole('switch')).toHaveCount(0)
})

test('390px keeps the navigation drawer whatever the sidebar setting, and the view menu offers only what fits', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await login(page)
  await mockTools(page)
  await page.addInitScript(() => localStorage.setItem('hub.reader.view', JSON.stringify({ sidebar: false, outline: false, smallText: false, fullWidth: false })))
  await openDocument(page)
  await expect(page.getByRole('button', { name: 'Show sidebar', exact: true })).toBeHidden()
  const menu = page.getByRole('button', { name: 'Open document navigation', exact: true })
  await menu.click()
  const drawer = page.getByRole('dialog', { name: 'Document navigation', exact: true })
  await expect(drawer).toBeVisible()
  await expect(drawer.getByRole('navigation', { name: 'Project documents', exact: true })).toBeVisible()
  await expect(drawer.getByRole('button', { name: 'Hide sidebar', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(menu).toBeFocused()

  await expect(article(page)).toHaveCSS('font-size', '16px')
  await openMenu(page)
  await expect(option(page, 'Table of contents')).toBeHidden()
  await expect(option(page, 'Full width')).toBeVisible()
  await option(page, 'Small text').click()
  await expect(article(page)).toHaveCSS('font-size', '15px')
  await noOverflow(page)
})

test('a shared document offers the view menu but no sidebar controls', async ({ page }) => {
  await page.goto('/s/review-document-link-only')
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /sidebar/ })).toHaveCount(0)
  await expect(outline(page)).toBeVisible()
  await openMenu(page)
  await option(page, 'Table of contents').click()
  await option(page, 'Full width').click()
  await expect(outline(page)).toBeHidden()
  await expect(article(page)).toHaveCSS('max-width', 'none')
  await page.reload()
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  await expect(outline(page)).toBeHidden()
  await expect(article(page)).toHaveCSS('max-width', 'none')
  await openMenu(page)
  await option(page, 'Table of contents').click()
  await expect(outline(page)).toBeVisible()
})
