// Auth — password (scrypt hash) and HMAC-signed cookies.
// Config lives in .env.local: MOA_PASSWORD_HASH (generated by scripts/set-password.mjs) + MOA_SECRET.
// Cookie format (must match the WebCrypto verification in middleware):
//   moa_owner = <expiryMs>.<hmacHex("owner:"+expiryMs)>            — legacy owner (=admin) login
//   moa_user  = <base64url({u,r,exp})>.<hmacHex("user:"+base64url)> — team account (users.json)
//   moa_share = <base64url(scopeJSON)>.<hmacHex("share:"+base64url)>
import crypto from 'node:crypto'

export const SECRET = process.env.MOA_SECRET || ''
export const PASSWORD_HASH = process.env.MOA_PASSWORD_HASH || ''
export const NO_AUTH = process.env.MOA_NO_AUTH === '1'

export const OWNER_TTL = 30 * 24 * 3600 * 1000 // 30 days
export const USER_TTL = 7 * 24 * 3600 * 1000 // 7 days — upper bound for an account disable to reach page level (APIs enforce immediately)
export const SHARE_TTL = 6 * 3600 * 1000 // 6 hours — renewed whenever the doc is reopened, so this caps the revocation delay

const hmac = (msg) => crypto.createHmac('sha256', SECRET).update(msg).digest('hex')

// scrypt hash format: scrypt:<saltHex>:<hashHex> — avoids `$`, which gets eaten by .env variable expansion
export const hashPassword = (pw) => {
  const salt = crypto.randomBytes(16).toString('hex')
  const hash = crypto.scryptSync(String(pw), salt, 32).toString('hex')
  return `scrypt:${salt}:${hash}`
}
export const verifyHash = (pw, stored) => {
  const [kind, salt, hash] = String(stored || '').split(':')
  if (kind !== 'scrypt' || !salt || !hash) return false
  const got = crypto.scryptSync(String(pw), salt, 32).toString('hex')
  try { return crypto.timingSafeEqual(Buffer.from(got), Buffer.from(hash)) } catch { return false }
}
export const verifyPassword = (pw) => verifyHash(pw, PASSWORD_HASH)

export const parseCookies = (req) => {
  const out = {}
  for (const kv of (req.headers.get('cookie') || '').split(';')) {
    const i = kv.indexOf('=')
    if (i > 0) out[kv.slice(0, i).trim()] = decodeURIComponent(kv.slice(i + 1).trim())
  }
  return out
}

export const mintOwnerCookie = () => {
  const exp = Date.now() + OWNER_TTL
  return `${exp}.${hmac('owner:' + exp)}`
}
export const isOwner = (req) => {
  if (NO_AUTH) return true
  if (!SECRET) return false
  const v = parseCookies(req).moa_owner || ''
  const [exp, sig] = v.split('.')
  return !!exp && !!sig && sig === hmac('owner:' + exp) && Number(exp) > Date.now()
}

// Team account cookie — { u: userId, r: 'admin'|'member', exp }. getAuth in lib/api.mjs cross-checks against users.json.
export const mintUserCookie = (user) => {
  const exp = Date.now() + USER_TTL
  const b = Buffer.from(JSON.stringify({ u: user.id, r: user.role, exp })).toString('base64url')
  return `${b}.${hmac('user:' + b)}`
}
export const readUserCookie = (req) => {
  if (!SECRET) return null
  const v = parseCookies(req).moa_user || ''
  const [b, sig] = v.split('.')
  if (!b || !sig || sig !== hmac('user:' + b)) return null
  try {
    const c = JSON.parse(Buffer.from(b, 'base64url').toString('utf8'))
    return c.exp > Date.now() ? c : null
  } catch { return null }
}

// Share scope: { t: token, s: slug, d: doc, m: [media path prefixes], a: [API prefixes], exp }
export const mintShareCookie = (scope) => {
  const b = Buffer.from(JSON.stringify(scope)).toString('base64url')
  return `${b}.${hmac('share:' + b)}`
}
export const readShareScope = (req) => {
  if (!SECRET) return null
  const v = parseCookies(req).moa_share || ''
  const [b, sig] = v.split('.')
  if (!b || !sig || sig !== hmac('share:' + b)) return null
  try {
    const scope = JSON.parse(Buffer.from(b, 'base64url').toString('utf8'))
    return scope.exp > Date.now() ? scope : null
  } catch { return null }
}

export const ownerSetCookie = () =>
  `moa_owner=${mintOwnerCookie()}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${OWNER_TTL / 1000}`
export const userSetCookie = (user) =>
  `moa_user=${mintUserCookie(user)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${USER_TTL / 1000}`
export const shareSetCookie = (scope) =>
  `moa_share=${mintShareCookie(scope)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${SHARE_TTL / 1000}`
